import FormatTyp from '../enums/common.enum';
export {
  DEFAULT_TABLE_LAYOUT,
  FA1RolaPodmiotu3,
  FA2RolaPodmiotu3,
  FA3RolaPodmiotu3,
  FormaPlatnosci,
  getTaxpayerStatusDescription,
  normalizeTaxpayerStatus,
  Procedura,
  RodzajTransportu,
  TAXPAYER_STATUS,
  TRodzajFaktury,
  TRolaPodmiotuUpowaznionegoFA1,
  TRolaPodmiotuUpowaznionegoFA2,
  TRolaPodmiotuUpowaznionegoFA3,
  TStawkaPodatku_FA1,
  TStawkaPodatku_FA2,
  TStawkaPodatku_FA3,
  TypKorekty,
  TypRachunkowWlasnych,
} from './FA.const';

export const Kraj: Record<string, string> = {
  AF: 'Afganistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algieria',
  AD: 'Andora',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarktyda',
  AG: 'Antigua i Barbuda',
  AN: 'Antyle Holenderskie',
  SA: 'Arabia Saudyjska',
  AR: 'Argentyna',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbejdżan',
  BS: 'Bahamy',
  BH: 'Bahrajn',
  BD: 'Bangladesz',
  BB: 'Barbados',
  BE: 'Belgia',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermudy',
  BT: 'Bhutan',
  BY: 'Białoruś',
  BO: 'Boliwia',
  BQ: 'Bonaire, Sint Eustatius i Saba',
  BA: 'Bośnia i Hercegowina',
  BW: 'Botswana',
  BR: 'Brazylia',
  BN: 'Brunei Darussalam',
  IO: 'Brytyjskie Terytorium Oceanu Indyjskiego',
  BG: 'Bułgaria',
  BF: 'Burkina faso',
  BI: 'Burundi',
  XC: 'Ceuta',
  CL: 'Chile',
  CN: 'Chiny',
  HR: 'Chorwacja',
  CW: 'Curaçao',
  CY: 'Cypr',
  TD: 'Czad',
  ME: 'Czarnogóra',
  DK: 'Dania',
  DM: 'Dominika',
  DO: 'Dominikana',
  DJ: 'Dżibuti',
  EG: 'Egipt',
  EC: 'Ekwador',
  ER: 'Erytrea',
  EE: 'Estonia',
  ET: 'Etiopia',
  FK: 'Falklandy',
  FJ: 'Fidżi Republika',
  PH: 'Filipiny',
  FI: 'Finlandia',
  FR: 'Francja',
  TF: 'Francuskie Terytorium Południowe',
  GA: 'Gabon',
  GM: 'Gambia',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Grecja',
  GD: 'Grenada',
  GL: 'Grenlandia',
  GE: 'Gruzja',
  GU: 'Guam',
  GG: 'Guernsey',
  GY: 'Gujana',
  GF: 'Gujana Francuska',
  GP: 'Gwadelupa',
  GT: 'Gwatemala',
  GN: 'Gwinea',
  GQ: 'Gwinea Równikowa',
  GW: 'Gwinea Bissau',
  HT: 'Haiti',
  ES: 'Hiszpania',
  HN: 'Honduras',
  HK: 'Hongkong',
  IN: 'Indie',
  ID: 'Indonezja',
  IQ: 'Irak',
  IR: 'Iran',
  IE: 'Irlandia',
  IS: 'Islandia',
  IL: 'Izrael',
  JM: 'Jamajka',
  JP: 'Japonia',
  YE: 'Jemen',
  JE: 'Jersey',
  JO: 'Jordania',
  KY: 'Kajmany',
  KH: 'Kambodża',
  CM: 'Kamerun',
  CA: 'Kanada',
  QA: 'Katar',
  KZ: 'Kazachstan',
  KE: 'Kenia',
  KG: 'Kirgistan',
  KI: 'Kiribati',
  CO: 'Kolumbia',
  KM: 'Komory',
  CG: 'Kongo',
  CD: 'Kongo, Republika Demokratyczna',
  KP: 'Koreańska Republika Ludowo-Demokratyczna',
  XK: 'Kosowo',
  CR: 'Kostaryka',
  CU: 'Kuba',
  KW: 'Kuwejt',
  LA: 'Laos',
  LS: 'Lesotho',
  LB: 'Liban',
  LR: 'Liberia',
  LY: 'Libia',
  LI: 'Liechtenstein',
  LT: 'Litwa',
  LV: 'Łotwa',
  LU: 'Luksemburg',
  MK: 'Macedonia',
  MG: 'Madagaskar',
  YT: 'Majotta',
  MO: 'Makau',
  MW: 'Malawi',
  MV: 'Malediwy',
  MY: 'Malezja',
  ML: 'Mali',
  MT: 'Malta',
  MP: 'Mariany Północne',
  MA: 'Maroko',
  MQ: 'Martynika',
  MR: 'Mauretania',
  MU: 'Mauritius',
  MX: 'Meksyk',
  XL: 'Melilla',
  FM: 'Mikronezja',
  UM: 'Minor',
  MD: 'Mołdowa',
  MC: 'Monako',
  MN: 'Mongolia',
  MS: 'Montserrat',
  MZ: 'Mozambik',
  MM: 'Myanmar (Burma)',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Niderlandy (Holandia)',
  DE: 'Niemcy',
  NE: 'Niger',
  NG: 'Nigeria',
  NI: 'Nikaragua',
  NU: 'Niue',
  NF: 'Norfolk',
  NO: 'Norwegia',
  NC: 'Nowa Kaledonia',
  NZ: 'Nowa Zelandia',
  PS: 'Okupowane Terytorium Palestyny',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PA: 'Panama',
  PG: 'Papua Nowa Gwinea',
  PY: 'Paragwaj',
  PE: 'Peru',
  PN: 'Pitcairn',
  PF: 'Polinezja Francuska',
  PL: 'Polska',
  GS: 'Południowa Georgia i Połud.Wyspy Sandwich',
  PT: 'Portugalia',
  PR: 'Portoryko',
  CF: 'Rep.środkowoafrykańska',
  CZ: 'Republika Czeska',
  KR: 'Republika Korei',
  ZA: 'Republika Południowej Afryki',
  RE: 'Reunion',
  RU: 'Rosja',
  RO: 'Rumunia',
  RW: 'Rwanda',
  EH: 'Sahara Zachodnia',
  BL: 'Saint Barthelemy',
  KN: 'Saint Kitts i Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  VC: 'Saint Vincent i Grenadyny',
  SV: 'Salwador',
  WS: 'Samoa',
  AS: 'Samoa Amerykańskie',
  SM: 'San Marino',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seszele',
  SL: 'Sierra Leone',
  SG: 'Singapur',
  SK: 'Słowacja',
  SI: 'Słowenia',
  SO: 'Somalia',
  LK: 'Sri Lanka',
  PM: 'Saint Pierre i Miquelon',
  US: 'Stany Zjednoczone Ameryki',
  SZ: 'Suazi',
  SD: 'Sudan',
  SS: 'Sudan Południowy',
  SR: 'Surinam',
  SJ: 'Svalbard i Jan Mayen',
  SH: 'Święta Helena',
  SY: 'Syria',
  CH: 'Szwajcaria',
  SE: 'Szwecja',
  TJ: 'Tadżykistan',
  TH: 'Tajlandia',
  TW: 'Tajwan',
  TZ: 'Tanzania',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trynidad i Tobago',
  TN: 'Tunezja',
  TR: 'Turcja',
  TM: 'Turkmenistan',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraina',
  UY: 'Urugwaj',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  WF: 'Wallis i Futuna',
  VA: 'Watykan',
  HU: 'Węgry',
  VE: 'Wenezuela',
  GB: 'Wielka Brytania',
  VN: 'Wietnam',
  IT: 'Włochy',
  TL: 'Wschodni Timor',
  CI: 'Wybrzeże Kości Słoniowej',
  BV: 'Wyspa Bouveta',
  CX: 'Wyspa Bożego Narodzenia',
  IM: 'Wyspa Man',
  SX: 'Wyspa Sint Maarten (część holenderska wyspy)',
  CK: 'Wyspy Cooka',
  VI: 'Wyspy Dziewicze-USA',
  VG: 'Wyspy Dziewicze-W.B.',
  HM: 'Wyspy Heard i Mcdonald',
  CC: 'Wyspy Kokosowe (Keelinga)',
  MH: 'Wyspy Marshalla',
  FO: 'Wyspy Owcze',
  SB: 'Wyspy Salomona',
  ST: 'Wyspy Świętego Tomasza i Książęca',
  TC: 'Wyspy Turks i Caicos',
  ZM: 'Zambia',
  CV: 'Zielony Przylądek',
  ZW: 'Zimbabwe',
  AE: 'Zjednoczone Emiraty Arabskie',
  XI: 'Zjednoczone Królestwo (Irlandia Północna)',
};

export const TableDataType: Record<string, FormatTyp> = {
  date: FormatTyp.Date,
  datetime: FormatTyp.DateTime,
  dec: FormatTyp.Currency,
  int: FormatTyp.Currency,
  time: FormatTyp.Time,
  txt: FormatTyp.Value,
};

export const TypLadunku: Record<string, string> = {
  '1': 'Bańka',
  '2': 'Beczka',
  '3': 'Butla',
  '4': 'Karton',
  '5': 'Kanister',
  '6': 'Klatka',
  '7': 'Kontener',
  '8': 'Kosz/koszyk',
  '9': 'Łubianka',
  '10': 'Opakowanie zbiorcze',
  '11': 'Paczka',
  '12': 'Pakiet',
  '13': 'Paleta',
  '14': 'Pojemnik',
  '15': 'Pojemnik do ładunków masowych stałych',
  '16': 'Pojemnik do ładunków masowych w postaci płynnej',
  '17': 'Pudełko',
  '18': 'Puszka',
  '19': 'Skrzynia',
  '20': 'Worek',
};
